name: first workflow
on: workflow_dispatch

josbs:
  first-job:
  runs-on: ubuntu-latest
  steps:
    - name : Print Greeting
      run: echo " Hello World"

    - name: Print Goodbye
      run: echo "done - bye"
  
